-- partição em PRODUTO
ALTER TABLE Produto
PARTITION BY KEY(id)
PARTITIONS 3;

-- partição em MateriaPrima
ALTER TABLE MateriaPrima
PARTITION BY KEY(id)
PARTITIONS 3;

-- partição em Cliente
ALTER TABLE Cliente
PARTITION BY KEY(id)
PARTITIONS 4;

-- partição na tabela de venda
ALTER TABLE Venda 
 PARTITION BY RANGE( YEAR(data_venda) ) (
    PARTITION p0 VALUES LESS THAN (2018),
    PARTITION p1 VALUES LESS THAN (2019),
    PARTITION p2 VALUES LESS THAN (2020),
    PARTITION p3 VALUES LESS THAN (2021),
    PARTITION p4 VALUES LESS THAN (2022),
	PARTITION p5 VALUES LESS THAN MAXVALUE
);